const assert=require('node:assert');
const html=require('node:fs').readFileSync('index.html','utf8');
const worker=require('node:fs').readFileSync('sw.js','utf8');
const listen=html.match(/<main id="listen"[\s\S]*?<main id="test"/)[0];

assert(listen.includes('PLXRewNkdAh9XyUiNo8xRt365g09gb-nkz'));
assert(listen.includes('./trainer.html'));
assert(!listen.includes('onclick="speak('));
assert(html.includes('<main id="duo"'));
assert(html.includes('<main id="source"'));
assert(html.includes('function resetDuo()'));
assert(html.includes('วรรคแรกคืออะไร?'));
assert(html.includes('สถานการณ์นี้ต้องใช้บทไหน?'));
assert(html.includes('วรรคถัดไปคืออะไร?'));
assert(html.includes('const duoOrderSteps='));
assert(html.includes('const duoCoreSteps='));
assert(html.includes('const duoGuidedSteps='));
assert(html.includes('const duoResponseSteps='));
assert(html.includes("setDuoMode('order')"));
assert(html.includes("setDuoMode('core')"));
assert(html.includes("setDuoMode('guided')"));
assert(html.includes("setDuoMode('response')"));
assert(html.includes("setDuoExercise('words')"));
assert(html.includes("setDuoExercise('hooks')"));
assert(html.includes('function renderHookStudy()'));
assert(html.includes('const SETS={core:[0,1,2,3,5,8,13],guided:[4,6,7]}'));
assert(html.includes('function setDuoSet(index)'));
assert(html.includes('function setUnlocked(index)'));
assert(html.includes('localStorage.getItem(\'duo6\')'));
assert(html.includes("setDuoMode('review')"));
assert(html.includes('function renderReview()'));
assert(html.includes('function markHardDuo(lesson,line,b)'));
assert(html.includes('function addHard(lesson,line)'));
assert(html.includes('แตะบัตรเพื่อดูความหมาย'));
assert(html.includes('.pali{border:1px solid var(--l);border-left:1px solid var(--l)}'));
assert(html.includes('h1{font-size:clamp(28px,5vw,38px)'));
assert(html.includes('src="./favicon.svg"')&&html.includes('class="brand-mark"'));
assert(html.includes('function checkWordDuo()'));
assert(html.includes("replace(/^\\d+\\s*/,'').replace(/\\s*\\(3 จบ\\)$/,'')"));
assert(html.includes('const duoCoreSteps=lineSteps([0,1,2,3,5,8,13])'));
assert(html.includes('const duoGuidedSteps=lineSteps([4,6,7])'));
assert(html.includes("localStorage.getItem('duo5')"));
assert(html.includes("['อุกาสะ','โอกาส → ขอโอกาส']"));
assert(html.includes("['วันทามิ','วันทา/ไหว้ → ข้าพเจ้าไหว้']"));
assert(html.includes("['เม','me → แก่ฉัน/ของฉัน']"));
assert(html.includes("['นัตถิ','nothing → ไม่มี']"));
assert(html.includes('function memory(i,open=false)'));
assert((html.match(/\$\{memory\(/g)||[]).length>=4);
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(require('node:fs').existsSync(file)&&html.includes('./'+file));
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(worker.includes('./'+file));
assert(html.includes("show('settings',this)"));
assert(html.includes('id="settingsBody"'));
assert(html.includes("const geminiKeyStore='openOrdinationGeminiKey'"));
assert(html.includes('function saveGeminiKey()'));
assert(html.includes('function clearGeminiKey()'));
assert(html.includes('function setGeminiPasscode()'));
assert(html.includes('function unlockGeminiSettings()'));
assert(html.includes("geminiPassStore='openOrdinationGeminiPasscode'"));
assert(html.includes("show('speak',this)"));
assert(html.includes('function startSpeechRecording()'));
assert(html.includes('function transcribeSpeech(blob,expected)'));
assert(html.includes("model:'gemini-3.5-transcribe'"));
assert(html.includes('function scoreSpeech(expected,heard)'));
assert(html.includes("document.getElementById('speechResult').innerHTML"));
assert(!html.includes("'Api-Revision':'2026-05-20'"));
assert(html.includes('setTimeout(stopSpeechRecording,12000)'));
assert(html.includes("filter(step=>step.type==='model_output')"));
assert(html.includes("model:'models/gemini-3.5-transcribe-live'"));
assert(html.includes('function startLiveSpeech()'));
assert(html.includes('function pcmBase64(samples,rate)'));
assert(html.includes('nextSpeechPractice();setTimeout(()=>liveAdvancing=false,600)'));
assert(worker.includes("open-ordination-v29"));
const lessons=new Function('return ['+html.match(/const S=\[([\s\S]*?)\n\];/)[1]+']')();
for(const line of lessons[10].p.split('\n')) assert.equal(line.split(' — ')[1],'นัตถิ ภันเต');
for(const line of lessons[11].p.split('\n')) assert.equal(line.split(' — ')[1],'อามะ ภันเต');
console.log('four practice categories, YouTube audio, and source pages are present');
