const assert=require('node:assert');
const html=require('node:fs').readFileSync('index.html','utf8');
const worker=require('node:fs').readFileSync('sw.js','utf8');
const listen=html.match(/<main id="listen"[\s\S]*?<main id="test"/)[0];

assert(listen.includes('PLXRewNkdAh9XyUiNo8xRt365g09gb-nkz'));
assert(listen.includes('./trainer.html'));
assert(!listen.includes('onclick="speak('));
assert(html.includes('<main id="duo"'));
assert(html.includes('<main id="source"'));
assert(html.includes('function resetDuo()'));
assert(html.includes('วรรคแรกคืออะไร?'));
assert(html.includes('สถานการณ์นี้ต้องใช้บทไหน?'));
assert(html.includes('วรรคถัดไปคืออะไร?'));
assert(html.includes('const duoOrderSteps='));
assert(html.includes('const duoCoreSteps='));
assert(html.includes('const duoGuidedSteps='));
assert(html.includes('const duoResponseSteps='));
assert(html.includes("setDuoMode('order')"));
assert(html.includes("setDuoMode('core')"));
assert(html.includes("setDuoMode('guided')"));
assert(html.includes("setDuoMode('response')"));
assert(html.includes("setDuoExercise('words')"));
assert(html.includes("setDuoExercise('hooks')"));
assert(html.includes('function renderHookStudy()'));
assert(html.includes('const SETS={core:[0,1,2,3,5,8,13],guided:[4,6,7]}'));
assert(html.includes('function setDuoSet(index)'));
assert(html.includes('function setUnlocked(index)'));
assert(html.includes('localStorage.getItem(\'duo6\')'));
assert(html.includes("setDuoMode('review')"));
assert(html.includes('function renderReview()'));
assert(html.includes('function markHardDuo(lesson,line,b)'));
assert(html.includes('function addHard(lesson,line)'));
assert(html.includes('แตะบัตรเพื่อดูความหมาย'));
assert(html.includes('.pali{border:1px solid var(--l);border-left:1px solid var(--l)}'));
assert(html.includes('h1{font-size:clamp(28px,5vw,38px)'));
assert(html.includes('src="./favicon.svg"')&&html.includes('class="brand-mark"'));
assert(html.includes('function checkWordDuo()'));
assert(html.includes('const duoCoreSteps=lineSteps([0,1,2,3,5,8,13])'));
assert(html.includes('const duoGuidedSteps=lineSteps([4,6,7])'));
assert(html.includes("localStorage.getItem('duo5')"));
assert(html.includes("['อุกาสะ','โอกาส → ขอโอกาส']"));
assert(html.includes("['วันทามิ','วันทา/ไหว้ → ข้าพเจ้าไหว้']"));
assert(html.includes("['เม','me → แก่ฉัน/ของฉัน']"));
assert(html.includes("['นัตถิ','nothing → ไม่มี']"));
assert(html.includes('function memory(i,open=false)'));
assert((html.match(/\$\{memory\(/g)||[]).length>=4);
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(require('node:fs').existsSync(file)&&html.includes('./'+file));
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(worker.includes('./'+file));
assert(html.includes("show('settings',this)"));
assert(html.includes('id="settingsBody"'));
assert(html.includes("const geminiKeyStore='openOrdinationGeminiKey'"));
assert(html.includes('function saveGeminiKey()'));
assert(html.includes('function clearGeminiKey()'));
assert(html.includes('function setGeminiPasscode()'));
assert(html.includes('function unlockGeminiSettings()'));
assert(html.includes("geminiPassStore='openOrdinationGeminiPasscode'"));
assert(html.includes("show('speak',this)"));
assert(html.includes('function startSpeechRecording()'));
assert(html.includes('function transcribeSpeech(blob,expected)'));
assert(html.includes("model:'gemini-3.5-transcribe'"));
assert(html.includes('function scoreSpeech(expected,heard)'));
assert(html.includes("document.getElementById('speechResult').innerHTML"));
assert(!html.includes("'Api-Revision':'2026-05-20'"));
assert(html.includes('setTimeout(stopSpeechRecording,12000)'));
assert(html.includes("filter(step=>step.type==='model_output')"));
assert(html.includes("model:'models/gemini-3.5-transcribe-live'"));
assert(html.includes('function startLiveSpeech()'));
assert(html.includes('function pcmBase64(samples,rate)'));
assert(html.includes('nextSpeechPractice();setTimeout(()=>{liveTranscript='));
assert(html.includes('if(message.setupComplete){clearTimeout(liveReadyTimer);liveNotice='));
assert(html.includes('Gemini Live ไม่พร้อมภายใน 8 วินาที'));
assert(html.includes("typeof event.data==='string'?event.data:await event.data.text()"));
assert(html.includes("liveFinalTranscript=(liveFinalTranscript+' '+finalText).trim()"));
assert(html.includes("speechScoreStore='openOrdinationSpeechScore'"));
assert(html.includes('function scoreSpeech(expected,heard)'));
assert(html.includes("liveFinalTranscript='';liveAdvancing=false},1600"));
assert(worker.includes("open-ordination-v36"));
const lessons=new Function('return ['+html.match(/const S=\[([\s\S]*?)\n\];/)[1]+']')();
for(const line of lessons[10].p.split('\n')) assert.equal(line.split(' — ')[1],'นัตถิ ภันเต');
for(const line of lessons[11].p.split('\n')) assert.equal(line.split(' — ')[1],'อามะ ภันเต');
console.log('four practice categories, YouTube audio, and source pages are present');
const sourceCode=html.slice(html.indexOf('const S=['),html.indexOf('// ponytail: one shared list'));
const {S,SOURCE_CONTEXT,lessonMarkup}=new Function(sourceCode+';return {S,SOURCE_CONTEXT,lessonMarkup}')();
assert(S[8].p.startsWith('อุกาสะ การุญญัง กัตวา, นิสสะยัง เทถะ เม ภันเต'));
assert(S[8].p.includes('อัชชะตัคเค ทานิเถโร มัยหังภาโร อะหัมปิ เถรัสสะ ภาโร'));
assert(S[7].p.includes('ชาตะรูปะ ระชะตะ ปะฏิคคะหะณา'));
assert(S[12].p.includes('อายัสมา วะระโท นามะ.'));
const lesson8=lessonMarkup(S[8]);
assert(lesson8.indexOf('โหหิ')<lesson8.indexOf('ปฏิรูปัง'));
assert(lesson8.indexOf('สัมปฏิจฉามิ')<lesson8.indexOf('อัชชะตัคเค'));
assert.equal((lesson8.match(/สัมปฏิจฉามิ/g)||[]).length,3);
const lesson6=lessonMarkup(S[6]);
assert(lesson6.indexOf('ยะมะหัง')<lesson6.indexOf('พุทธัง'));
assert(lesson6.indexOf('ตะติยัมปิ สังฆัง')<lesson6.indexOf('นิฏฐิตัง'));
const linesCode=html.match(/const duoLines=[\s\S]*?(?=let selectedWords)/)[0];
const drills=new Function('S','SOURCE_CONTEXT',linesCode+';return {duoLines,duoCoreSteps,duoResponseSteps}')(S,SOURCE_CONTEXT);
for(const {lesson,line} of drills.duoCoreSteps){assert(!/พระพูด|ท่าทาง|ปฏิรูปัง|โอปายิกัง|ปาสาทิเก/.test(drills.duoLines[lesson][line]));}
assert(drills.duoLines[7].every(line=>!/^\d|^\./.test(line)));
assert(drills.duoResponseSteps.some(s=>s.prompt==='ปฏิรูปัง'&&s.answer==='อุกาสะ สัมปฏิจฉามิ'));
assert(drills.duoResponseSteps.some(s=>s.prompt==='ยะมะหัง วะทามิตัง วะเทหิ'&&s.answer==='อามะ ภันเต'));
new Function(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
console.log('source corrections, response order, and recitation boundaries verified');
const migrate=new Function('duo','localStorage','speechStepStore','speechScoreStore',html.slice(html.indexOf('if(duo.sourceVersion'),html.indexOf('duo.set??=')));
const saved=new Map(),storage={setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};
const progress={setProgress:{coreChoice0:{step:5},coreWords8:{step:3},coreChoice1:{step:2},guidedChoice7:{step:4}},hard:{old:{lesson:8},keep:{lesson:7}},order:{step:9,score:8},response:{step:5}};
migrate(progress,storage,'speechStep','speechScore');
assert.deepEqual(progress.order,{step:9,score:8});
assert.equal(progress.setProgress.coreChoice1.step,2);
assert.equal(progress.setProgress.guidedChoice7.step,4);
assert(!progress.setProgress.coreChoice0&&!progress.setProgress.coreWords8);
assert(progress.hard.keep&&!progress.hard.old);
assert(saved.has('duo6-before-source-correction'));
progress.response.step=2;
migrate(progress,storage,'speechStep','speechScore');
assert.equal(progress.response.step,2);
