const assert=require('node:assert');
const html=require('node:fs').readFileSync('index.html','utf8');
const worker=require('node:fs').readFileSync('sw.js','utf8');
const listen=html.match(/<main id="listen"[\s\S]*?<main id="test"/)[0];

assert(listen.includes('PLXRewNkdAh9XyUiNo8xRt365g09gb-nkz'));
assert(listen.includes('./trainer.html'));
assert(!listen.includes('onclick="speak('));
assert(html.includes('<main id="duo"'));
assert(html.includes('<main id="source"'));
assert(html.includes('function resetDuo()'));
assert(html.includes('วรรคแรกคืออะไร?'));
assert(html.includes('สถานการณ์นี้ต้องใช้บทไหน?'));
assert(html.includes('วรรคถัดไปคืออะไร?'));
assert(html.includes('const duoOrderSteps='));
assert(html.includes('const duoCoreSteps='));
assert(html.includes('const duoGuidedSteps='));
assert(html.includes('const duoResponseSteps='));
assert(html.includes("setDuoMode('order')"));
assert(html.includes("setDuoMode('core')"));
assert(html.includes("setDuoMode('guided')"));
assert(html.includes("setDuoMode('response')"));
assert(html.includes("setDuoExercise('words')"));
assert(html.includes('function checkWordDuo()'));
assert(html.includes("replace(/^\\d+\\s*/,'').replace(/\\s*\\(3 จบ\\)$/,'')"));
assert(html.includes('const duoCoreSteps=lineSteps([0,1,2,3,5,8,13])'));
assert(html.includes('const duoGuidedSteps=lineSteps([4,6,7])'));
assert(html.includes("localStorage.getItem('duo5')"));
assert(html.includes("['อุกาสะ','โอกาส → ขอโอกาส']"));
assert(html.includes("['วันทามิ','วันทา/ไหว้ → ข้าพเจ้าไหว้']"));
assert(html.includes('function memory(i,open=false)'));
assert((html.match(/\$\{memory\(/g)||[]).length>=4);
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(require('node:fs').existsSync(file)&&html.includes('./'+file));
for(const file of ['original-2807.jpg','original-2808.jpg','original-2809.jpg']) assert(worker.includes('./'+file));
assert(worker.includes("open-ordination-v14"));
const lessons=new Function('return ['+html.match(/const S=\[([\s\S]*?)\n\];/)[1]+']')();
for(const line of lessons[10].p.split('\n')) assert.equal(line.split(' — ')[1],'นัตถิ ภันเต');
for(const line of lessons[11].p.split('\n')) assert.equal(line.split(' — ')[1],'อามะ ภันเต');
console.log('four practice categories, YouTube audio, and source pages are present');
